steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/XinghanGuo1019/AI.git', '.']
  - name: 'gcr.io/cloud-builders/git'
    args: ['checkout', 'master'] 
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-app:$SHORT_SHA']
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workday-mcp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-app:$SHORT_SHA'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' 